### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by zamiang** [kitajchuk/node-squarespace-server#104]
After starting the server and logging in, I get this error. Looks like something in the squarespace API's login response has changed.

The error is coming from `squarespace-middleware` - happy to move this issue there if you think that is more appropriate.

```javascript
TypeError: Cannot read property 'loginUrl' of undefined
    at Request._callback (/Users/zamiang/.nvm/v0.10.33/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-middleware/squarespace-middleware.js:108:36)
    at Request.self.callback (/Users/zamiang/.nvm/v0.10.33/lib/node_modules/node-squarespace-server/node_modules/request/request.js:197:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/zamiang/.nvm/v0.10.33/lib/node_modules/node-squarespace-server/node_modules/request/request.js:1050:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/zamiang/.nvm/v0.10.33/lib/node_modules/node-squarespace-server/node_modules/request/request.js:996:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

**Comment by kitajchuk** [comment]
Try busting your cache locally. Also, are you using a trial mode account?

**Comment by zamiang** [comment]
@kitajchuk Doh! Thanks. I thought I did that but tried again and not it works.

**Comment by kitajchuk** [comment]
Cool. Glad it worked out for you :)
