### ISSUE TITLE
TypeError: Cannot read property...

### ISSUE THREAD

**Issue by mramitpatel** [kitajchuk/node-squarespace-server#105]
After I run ```sqs server``` and authenticate...
This error pops up seemingly during the authentication process since it doesn't post success.
```
TypeError: Cannot read property 'targetWebsite' of undefined
    at Request._callback (/usr/local/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-middleware/squarespace-middleware.js:108:22)
    at Request.self.callback (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:197:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:1050:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:996:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

**Comment by mramitpatel** [comment]
Also, I have verified im using:
* ```https``` and not ```http``` in my conf.
*  site-wide password enabled

**Comment by mramitpatel** [comment]
Solved. I mistakingly kept ```sandbox: trial``` in my conf despite being a paid account.
