### ISSUE TITLE
Search page does not work on local server

### ISSUE THREAD

**Issue by kitajchuk** [kitajchuk/node-squarespace-server#107]

**Comment by lyonsrob** [comment]
In version 0.4.24 I'm receiving this error when loading the search page locally. Looking at the .sqs-cache, the resulting files are blank. 

/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:908
    typeName = pageJson.collection.typeName;
                                  ^

TypeError: Cannot read property 'typeName' of undefined
    at getTemplateKey (/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:908:35)
    at Object.renderTemplate (/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:457:23)
    at /usr/local/lib/node_modules/node-squarespace-server/squarespace-server.js:264:29
    at /usr/local/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-middleware/squarespace-middleware.js:393:13
    at Request._callback (/usr/local/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-middleware/squarespace-middleware.js:314:9)
    at Request.self.callback (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:200:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:1041:10)
    at emitOne (events.js:95:20)
