### ISSUE TITLE
BLOCK ERROR - Empty block JSON

### ISSUE THREAD

**Issue by jarneuyt** [kitajchuk/node-squarespace-server#66]
Hey there! I'm trying to follow your Squarespace flow but I'm stuck in the end.
I'm able to start the server (sqs server) and log in. But after that, I get a message "This webpage is not available". See my terminal output below. Any ideas?

MacBook-Pro-Jarne-11:sqs_template jarneuytersprot$ sqs server
> sqs-server: Running site on localhost:5050
> sqs-server: AUTH - Login to Squarespace!
> sqs-server: GET - /
> sqs-server: CSS - reset
> sqs-server: LESS - base.less
> sqs-server: LESS - style.less
> sqs-server: Loading request from cache
> sqs-server: TEMPLATE - default.region
> sqs-middleware: BLOCK ERROR - Empty block JSON

TypeError: Cannot call method 'match' of undefined
    at Object.getAttrObj (/usr/local/lib/node_modules/node-squarespace-server/lib/functions.js:81:22)
    at getBlocks (/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:871:36)
    at /usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:937:25
    at Request._callback (/usr/local/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-middleware/squarespace-middleware.js:403:9)
    at Request.self.callback (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:373:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:1318:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:1266:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)

**Comment by jarneuyt** [comment]
If I remove the code below, it works.


<footer id="footer" class="footer">
        <squarespace:block-field id="footerBlocks" columns="12" />
</footer>

**Comment by kitajchuk** [comment]
Good find! Looks like I'm not running an important piece of code when bypassing error prone blocks:

```javascript
if ( !matched.length ) {
    callback( rendered );

} else {
    getBlocks();
}
```

**Comment by kitajchuk** [comment]
I just merged a fix in for this issue:
122f58a9e3412cf69ee1853b3a1b2ce9d0f9cab2

The new published package version:
node-squarespace-server@0.1.16

Let me know if that works and I'll close this issue out :)

**Comment by jarneuyt** [comment]
Seems to work! Thanks, I appreciate your work and help :)
