### ISSUE TITLE
Bug - Handle password protected pages

### ISSUE THREAD

**Issue by kitajchuk** [kitajchuk/node-squarespace-server#71]
Not sure we can, but they definitely don't work right now. Needs looking into.

**Comment by foleyatwork** [comment]
Currently working on a fix for this. Are you overwriting search parameters anywhere? I've been digging trying to find it, but when I write:

https://some-url.squarespace.com?password=whatever

The search parameter is removed.

**Comment by kitajchuk** [comment]
Hmm. Well, the password field for the middleware is for the sitewide password. For password protected pages, you get a form you need to enter the password in. Does that work the same as the sitewide password?

**Comment by kitajchuk** [comment]
My experience is that for passwords at the page specific level, you have to fill in that form.

**Comment by foleyatwork** [comment]
Yea, if you go to a password protected page with the password set as a search param, it will let you through. I thought refreshing with the search param in place would be a super easy way to get around this bug, but it's being overwritten.

**Comment by foleyatwork** [comment]
Basically, my approach was anytime you get a 401, send someone to a password page then refresh the page with the value of the password field set in the search parameter.

**Comment by kitajchuk** [comment]
Ok, this is weird. I'm actually getting password protected pages to just render locally without a password. I'm wondering if requesting via the modules middleware somehow breaks around this restriction...

**Comment by foleyatwork** [comment]
How are you requesting those pages? When I navigate through my site using node-squarespace-server, I get this response from password protected pages.

<pre><code>
TypeError: Cannot read property 'typeName' of undefined
   at getTemplateKey (/Users/kfoley/node-squarespace-server/squarespace-template.js:298:35)
   at Object.renderTemplate (/Users/kfoley/node-squarespace-server/squarespace-template.js:334:23)
   at renderResponse (/Users/kfoley/node-squarespace-server/squarespace-server.js:186:21)
   at onExpressRouterGET (/Users/kfoley/node-squarespace-server/squarespace-server.js:406:5)
   at Layer.handle [as handle_request] (/Users/kfoley/node-squarespace-server/node_modules/express/lib/router/layer.js:82:5)
   at next (/Users/kfoley/node-squarespace-server/node_modules/express/lib/router/route.js:100:13)
   at Route.dispatch (/Users/kfoley/node-squarespace-server/node_modules/express/lib/router/route.js:81:3)
   at Layer.handle [as handle_request] (/Users/kfoley/node-squarespace-server/node_modules/express/lib/router/layer.js:82:5)
   at /Users/kfoley/node-squarespace-server/node_modules/express/lib/router/index.js:234:24
   at Function.proto.process_params (/Users/kfoley/node-squarespace-server/node_modules/express/lib/router/index.js:312:12)
</code></pre>

**Comment by kitajchuk** [comment]
I think you can only get the HTML, not the JSON...

**Comment by kitajchuk** [comment]
No, it seems to be working for both.

**Comment by kitajchuk** [comment]
Are you all up to date on the module? I think 0.2.3 is the latest.

**Comment by foleyatwork** [comment]
Middleware is up-to-date but I might be a little behind on the server. I'll double check tomorrow and see if I can get more info on this one.

**Comment by kitajchuk** [comment]
Password protected pages work inherently now since the local server assumes the secure headers.
