### ISSUE TITLE
pageJson.collection undefined

### ISSUE THREAD

**Issue by tdrach** [kitajchuk/node-squarespace-server#82]
Thank you so much for spending the time making this module. 
I'm getting the following error:

```
TypeError: Cannot read property 'typeName' of undefined
   at getTemplateKey (/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:298:35)
   at Object.renderTemplate (/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:334:23)
   at renderResponse (/usr/local/lib/node_modules/node-squarespace-server/squarespace-server.js:187:21)
   at onExpressRouterGET (/usr/local/lib/node_modules/node-squarespace-server/squarespace-server.js:400:5)
   at Layer.handle [as handle_request] (/usr/local/lib/node_modules/node-squarespace-server/node_modules/express/lib/router/layer.js:82:5)
   at next (/usr/local/lib/node_modules/node-squarespace-server/node_modules/express/lib/router/route.js:100:13)
   at Route.dispatch (/usr/local/lib/node_modules/node-squarespace-server/node_modules/express/lib/router/route.js:81:3)
   at Layer.handle [as handle_request] (/usr/local/lib/node_modules/node-squarespace-server/node_modules/express/lib/router/layer.js:82:5)
   at /usr/local/lib/node_modules/node-squarespace-server/node_modules/express/lib/router/index.js:234:24
   at Function.proto.process_params (/usr/local/lib/node_modules/node-squarespace-server/node_modules/express/lib/router/index.js:312:12)
```

I double checked my siteUrl.
Any ideas on how to fix this problem?

**Comment by tdrach** [comment]
I found this was an issue with trial accounts with dev mode turned on. Using a dev sandbox account, no error is thrown, but ```undefined``` is now passed as the content.

**Comment by kitajchuk** [comment]
Do you have the `"sandbox": true` option set in your template.conf under the server config?

**Comment by tdrach** [comment]
I do, here's my ```server``` content in ```template.conf```
```
    "server": {
        "siteurl": "https://mysiteurl.squarespace.com",
        "sandbox": true
    }
```

**Comment by kitajchuk** [comment]
Ok, cool. Which template are you using? Also, can you do an `sqs buster` and run it again? Sometimes if you try to run the server before adding the "sandbox" option in the config it caches "undefined". You can check the `.sqs-cache` directory to see if this is the case. So subsequent requests load from cache and fail once sandbox config is present. Clearing local cache and starting fresh usually clears that up if this is the issue.

**Comment by tdrach** [comment]
That did it. Thank you so much for making this available, and your write up. This makes Squarespace development bearable.
