### ISSUE TITLE
 TypeError: Cannot read property 'folder' of null

### ISSUE THREAD

**Issue by sinakarimi** [kitajchuk/node-squarespace-server#88]
Everything was working fine, there were no changes made but then I suddenly started getting errors after I added a new folder in my squarespace website navigation.

```
$ sqs server
> sqs-server: Running site on localhost:5050
> sqs-server: AUTH - Login to Squarespace!
> sqs-server: GET - /
> sqs-server: TEMPLATE - gallery.list

TypeError: Cannot read property 'folder' of null
    at Object.Context.get (/usr/local/n/current/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-jsont/lib/jsontemplate.js:302:22)
    at /usr/local/n/current/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-jsont/lib/predicates.js:95:31
    at _DoPredicates (/usr/local/n/current/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-jsont/lib/jsontemplate.js:462:21)
    at _Execute (/usr/local/n/current/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-jsont/lib/jsontemplate.js:402:7)
    at _DoRepeatedSection (/usr/local/n/current/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-jsont/lib/jsontemplate.js:490:7)
    at _Execute (/usr/local/n/current/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-jsont/lib/jsontemplate.js:402:7)
    at _DoPredicates (/usr/local/n/current/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-jsont/lib/jsontemplate.js:464:7)
    at _Execute (/usr/local/n/current/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-jsont/lib/jsontemplate.js:402:7)
    at _DoRepeatedSection (/usr/local/n/current/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-jsont/lib/jsontemplate.js:490:7)
    at _Execute (/usr/local/n/current/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-jsont/lib/jsontemplate.js:402:7)

```

**Comment by sinakarimi** [comment]
Also just a quick note, I had followed all the steps in the troubleshooting section here https://github.com/kitajchuk/node-squarespace-server#troubleshooting and the error still occurs.

**Comment by kitajchuk** [comment]
Hmm, do you have any idea which line in your template may be causing the error?

**Comment by kitajchuk** [comment]
Also, are you on the latest version of the server?

**Comment by sinakarimi** [comment]
I haven't been able to identify which line is causing the error. I haven't made any reference to 'folder' anywhere in the template. The base template used for the project is this template here http://www.squarespace.com/templates/?q=wexley if that helps at all.

I might continue to do some more debugging tonight, it could very well be an issue with the template as I am unable to reproduce this error on other templates.

And yes, I am currently using version 0.1.30 of sqs.

**Comment by kitajchuk** [comment]
Great, thanks. I'll get that template running and try to reproduce :)

**Comment by kitajchuk** [comment]
@sinakarimi Is this still an issue for you? Late, I know, but a lot of work has been done recently with direct regards to folder-navigation support. Wondering if you still have this issue or use the server anymore?

**Comment by kitajchuk** [comment]
Closing this out. We can re-open it if its still bugging.
