### ISSUE TITLE
Can't boot server

### ISSUE THREAD

**Issue by mrmayfield** [kitajchuk/node-squarespace-server#99]
Trying to add 
```
"server": {
    "siteurl": "https://yoursite.squarespace.com",
    "sandbox": true
}
```

when this is my template.conf

```
{
  "name" : "Marquee",
  "author" : "Adam Parks, Riyaz Shaikh",

  "layouts" : {
    "default" : {
      "name" : "Default",
      "regions" : [ "site" ]
    }
  },

  "navigations" : [ {
      "title" : "Main Navigation",
      "name" : "mainNav"
  },
  {
      "title" : "Secondary Navigation",
      "name" : "secondaryNav"
  } ],

  "systemCollections" : [
    "products",
    "album"
  ],

  "stylesheets" : [
    "tweak.less",
    "global.less",
    "events.less",
    "gallery.less",
    "mobile.less"
  ]
}
```

but it blows up with syntax erros

```
undefined:35
"server": {
^
SyntaxError: Unexpected string
    at Object.parse (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-squarespace-server/bin/squarespace-server:54:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

My two guesses:
1) I don't have a 'developer template' set up correctly, wherein the code would be valid JSON and could have the server block added easily
2) The documentation is lagging behind some changes to template.conf

Any ideas? Thanks a lot!

**Comment by mrmayfield** [comment]
I'm tripping. Got it, thanks. :)
